const mockMovies = [
  {
    id: 1,
    genres: ["Science Fiction"],
    rating: 5,
    title: "Godzilla vs. Kong",
    description:
      "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
    poster: "./img/godzilla.png",
    url: "#",
  },
  {
    id: 1,
    genres: ["Science Fiction"],
    rating: 5,
    title: "Godzilla vs. Kong",
    description:
      "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
    poster: "./img/godzilla.png",
    url: "#",
  },
  {
    id: 1,
    genres: ["Science Fiction"],
    rating: 5,
    title: "Godzilla vs. Kong",
    description:
      "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
    poster: "./img/godzilla.png",
    url: "#",
  },
];

const mockReleases = [
  {
    id: 1,
    genres: ["Science Fiction"],
    rating: 3,
    title: "Wonder Woman",
    poster: "./img/wonder-woman.png",
    url: "#",
  },
  {
    id: 2,
    genres: ["Fantasy"],
    rating: 4,
    title: "Justice Leauge",
    poster: "./img/justice.png",
    url: "#",
  },
  {
    id: 3,
    genres: ["Fantasy"],
    rating: 4,
    title: "Mortal Kombat",
    poster: "./img/mortal.png",
    url: "#",
  },
  {
    id: 4,
    genres: ["Drama"],
    rating: 2,
    title: "Courier",
    poster: "./img/courier.png",
    url: "#",
  },
  {
    id: 5,
    genres: ["Action"],
    rating: 2,
    title: "Thunder Force",
    poster: "./img/thunder.png",
    url: "#",
  },
  {
    id: 6,
    genres: ["Animation"],
    rating: 4,
    title: "Amazing Maurice",
    poster: "./img/amazing.jpg",
    url: "#",
  },
  {
    id: 7,
    genres: ["Action"],
    rating: 2,
    title: "Avatar",
    poster: "./img/avatar.jpg",
    url: "#",
  },
  {
    id: 8,
    genres: ["Drama"],
    rating: 2,
    title: "operation",
    poster: "./img/operation.jpg",
    url: "#",
  },
];

const mockTvShows = [
  {
    id: 1,
    genres: ["Sci-fi & Fantasy"],
    rating: 5,
    title: "Game of thrones",
    poster: "./img/got.png",
    url: "#",
  },
  {
    id: 2,
    genres: ["Adventure"],
    rating: 4,
    title: "The Last of Us",
    poster: "./img/last.jpg",
    url: "#",
  },
  {
    id: 3,
    genres: ["Comedy"],
    rating: 5,
    title: "The Office",
    poster: "./img/office.jpg",
    url: "#",
  },
  {
    id: 4,
    genres: ["Action"],
    rating: 5,
    title: "The Boys",
    poster: "./img/boys.jpg",
    url: "#",
  },
  {
    id: 5,
    genres: ["Sci-fi & Fantasy"],
    rating: 3,
    title: "Winter Soldier",
    poster: "./img/winter.png",
    url: "#",
  },
  {
    id: 6,
    genres: ["Sci-fi & Fantasy"],
    rating: 3,
    title: "Wanda Vision",
    poster: "./img/wanda.png",
    url: "#",
  },
];
